In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nlp-getting-started/sample_submission.csv
/kaggle/input/nlp-getting-started/train.csv
/kaggle/input/nlp-getting-started/test.csv


# Approaches
Our first apporach is to just use the text and pass it through an Naive Bayes.

We may use the keyword/loc in late user

LLM?

In [55]:
df = pd.read_csv("/kaggle/input/nlp-getting-started/train.csv")

In [56]:
df = df.drop(["keyword", "location"], axis=1)

y_train = df["target"]
df = df.drop("target", axis=1)

In [57]:
from nltk import word_tokenize
X_train = df["text"].apply(word_tokenize)
X_train_text = X_train.apply(lambda tokens: ' '.join(tokens))

In [58]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train_text).toarray()

In [32]:
# from nltk import word_tokenize 

# X_train = df["text"].apply(word_tokenize)

In [33]:
import re
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer

In [60]:
#test data
df_test = pd.read_csv("/kaggle/input/nlp-getting-started/test.csv")

X_test = df_test.pop("text")
X_test = X_test.apply(word_tokenize)
X_test_text = X_test.apply(lambda tokens: ' '.join(tokens))

X_test_vec = vectorizer.transform(X_test_text).toarray()
print(X_test_vec)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [62]:
classifier = GaussianNB();
classifier.fit(X_train_vec, y_train)

y_pred = classifier.predict(X_test_vec)

In [64]:
print(y_pred)

[1 1 1 ... 1 1 1]


In [66]:
with open("submisson.csv", "w") as file:
    file.write("id, target")
    
    for i, pred in enumerate(y_pred):
        file.write(str(i) + ", " + str(pred) + "\n")