In [1]:
import numpy as np 
import pandas as pd

# Approaches
Our first apporach is to just use the text and pass it through an Naive Bayes.

We may use the keyword/loc in late user

LLM?

In [2]:
df = pd.read_csv("/kaggle/input/nlp-getting-started/train.csv")

In [3]:
df = df.drop(["keyword", "location"], axis=1)

y_train = df["target"]
df = df.drop("target", axis=1)

In [4]:
from nltk import word_tokenize
X_train = df["text"].apply(word_tokenize)
X_train_text = X_train.apply(lambda tokens: ' '.join(tokens))

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train_text).toarray()

In [6]:
# from nltk import word_tokenize 

# X_train = df["text"].apply(word_tokenize)

In [7]:
import re
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
#test data
df_test = pd.read_csv("/kaggle/input/nlp-getting-started/test.csv")

X_test = df_test.pop("text")
X_test = X_test.apply(word_tokenize)
X_test_text = X_test.apply(lambda tokens: ' '.join(tokens))

X_test_vec = vectorizer.transform(X_test_text).toarray()
print(X_test_vec)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
classifier = GaussianNB();
classifier.fit(X_train_vec, y_train)

y_pred = classifier.predict(X_test_vec)

In [10]:
submission = pd.read_csv('/kaggle/input/nlp-getting-started/sample_submission.csv')

submission['target'] = y_pred

submission.to_csv('submission.csv', index=False)

In [11]:
# with open("submisson.csv", "w") as file:
#     file.write("id, target \n")
    
#     for i, pred in enumerate(y_pred):
#         file.write(str(i) + ", " + str(pred) + "\n")